version: 2.1

orbs:

  node: circleci/node@4.1


jobs:

  build:

    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build app
          command: npm run build  

  test:
    docker:
      - image: cimg/node:15.1

    steps:
     
      - node/install-packages

      - run:
          name: Run tests
          command: npm test

  install-packages:
    docker:
      - image: cimg/node:15.1

    steps:
     
      - node/install-packages

      - run:
          name: Install dependencies
          command: npm install --save
  
workflows:

  build-test-and-deploy:
   jobs:
    - test 
    - build:
        requires:
         - test
    - install-packages

#express
#chalk
#dotenv
#mongoose
#mongoSanitize

