version: 2.1

orbs:

  node: circleci/node@4.1


jobs:

  start:

    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: start
          command: npm start  

  test:
    docker:
      - image: cimg/node:15.1

    steps:
     
      - node/install-packages

      - run:
          name: Run tests
          command: npm test

  
workflows:

  build-test-and-deploy:
   jobs:
    - test 
    - start:
        requires:
         - test
#express
#chalk
#dotenv
#mongoose
#mongoSanitize

